# Generated by Django 3.1.4 on 2022-05-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
