# Generated by Django 3.1.4 on 2022-04-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.business'),
        ),
    ]
