# Generated by Django 3.1.4 on 2022-04-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('lazy_seen', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
