# Generated by Django 3.1.4 on 2022-04-17 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitevisit',
            name='ipuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_ipuser', to='users.ipuser'),
        ),
        migrations.AddField(
            model_name='websitevisit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.business'),
        ),
        migrations.AddField(
            model_name='businessvisit',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.business'),
        ),
        migrations.AddField(
            model_name='businesspostcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesspostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.businesspost'),
        ),
        migrations.AddField(
            model_name='businesspost',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.business'),
        ),
        migrations.AddField(
            model_name='businesspost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.postcategory'),
        ),
        migrations.AddField(
            model_name='businesspost',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessdirection',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.business'),
        ),
        migrations.AddField(
            model_name='businessdirection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesscall',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.business'),
        ),
        migrations.AddField(
            model_name='businesscall',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.businesscategory'),
        ),
        migrations.AddField(
            model_name='business',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
