# Generated by Django 3.1.4 on 2022-04-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220418_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='low_thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='low_business_thumbnails'),
        ),
    ]
