# Generated by Django 3.1.4 on 2022-04-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20220418_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='low_thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='low_business_thumbnails'),
        ),
    ]
