# Generated by Django 3.1.4 on 2022-04-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220418_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_image',
            field=models.ImageField(default=None, null=True, upload_to='low_products_images'),
        ),
    ]
