# Generated by Django 3.1.4 on 2022-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_product_low_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
    ]
