# Generated by Django 3.1.4 on 2022-05-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20220517_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='low_thumbnail',
        ),
    ]
