# Generated by Django 3.1.4 on 2022-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_business_low_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='thumbnail',
            field=models.ImageField(default='DefaultBusinessThumbnail.png', upload_to='business_thumbnails'),
        ),
    ]
