# Generated by Django 3.1.4 on 2022-07-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20220708_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
