# Generated by Django 3.1.4 on 2022-07-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20220714_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteVisit',
        ),
    ]
