# Generated by Django 3.1.4 on 2022-04-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproductreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.productrating'),
        ),
    ]
