# Generated by Django 3.1.4 on 2022-07-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20220418_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrating',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
